# Generated by Django 5.0.1 on 2024-02-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0002_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='description',
        ),
        migrations.AddField(
            model_name='about',
            name='short_description',
            field=models.CharField(default='This is my role', max_length=200),
        ),
        migrations.AddField(
            model_name='about',
            name='summary',
            field=models.TextField(default='This is my breif summary'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(default='My Title', max_length=100),
        ),
    ]
