# Generated by Django 5.0.1 on 2024-02-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0003_remove_about_description_about_short_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('issued_by', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='certifications/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
